### ISSUE TITLE
Incompatibility with DokuWiki 2010-11-07

### ISSUE THREAD

**Issue by damascene** [znarf/dokuwiki-openid#1]
Hi, thank you for your work on the plugin.
The plugin does not seem to work with DokuWiki 2010-11-07. Could you please fix the problem.

I'm getting these lines after I chose to login using openID and enter my openid URL:
Warning: Call-time pass-by-reference has been deprecated in server_directories/wiki/lib/plugins/openid/Auth/OpenID/Consumer.php on line 1184

Warning: Call-time pass-by-reference has been deprecated in server_directories/wiki/lib/plugins/openid/Auth/Yadis/Manager.php on line 416

Warning: session_start() [function.session-start]: Cannot send session cookie - headers already sent by (output started at server_directories/wiki/lib/plugins/openid/Auth/OpenID/Consumer.php:1184) in server_directories/wiki/lib/plugins/openid/action.php on line 117

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at server_directories/wiki/lib/plugins/openid/Auth/OpenID/Consumer.php:1184) in server_directories/wiki/lib/plugins/openid/action.php on line 117

Warning: Cannot modify header information - headers already sent by (output started at server_directories/wiki/lib/plugins/openid/Auth/OpenID/Consumer.php:1184) in server_directories/wiki/lib/plugins/openid/action.php on line 99

**Comment by znarf** [comment]
A new version (2.2) was just issued. Does-it fix your issue ?

**Comment by damascene** [comment]
I'm sorry, It does not. I've used it with yahoo and launchpad.net openid

http://wiki.linuxac.org/doku.php?id=%D8%A8%D8%AF%D8%A7%D9%8A%D8%A9&do=openid

update: I hit the close button accidentally
